# Gemfile:
#   optional:
#     ':development':
#       - gem: byebug
#         version: '10.0.2'
remove_includes:
  - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
    rvm: 2.1.9
includes:
  - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
    rvm: 2.3.3
  - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
    rvm: 2.4.4
